plugins {
    id 'java'
}

repositories {
    mavenCentral()
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

// Add your dependencies here


// Add the "RepositorySetupTest" task here


task testQ3(type: Test) {
    description = "Runs the Question 3 (Rectangle) test."
    group = "verification"
    useJUnitPlatform()
    filter {
        includeTestsMatching "RectangleTest"
    }
    testClassesDirs = sourceSets.test.output.classesDirs
    classpath = sourceSets.test.runtimeClasspath
}

task testQ6(type: Test) {
    description = "Runs the Question 6 (Checkout) test."
    group = "verification"
    useJUnitPlatform()
    filter {
        includeTestsMatching "CheckoutTest"
    }
    testClassesDirs = sourceSets.test.output.classesDirs
    classpath = sourceSets.test.runtimeClasspath
}
