plugins {
    id 'java'
}

repositories {
    mavenCentral()
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

// Add your dependencies here


// Add the "RepositorySetupTest" task here



task testQ5(type: Test) {
    description = "Runs the Question 5 (Checkout) test."
    group = "verification"
    useJUnitPlatform()
    filter {
        includeTestsMatching "CheckoutTest"
    }
    testClassesDirs = sourceSets.test.output.classesDirs
    classpath = sourceSets.test.runtimeClasspath
}
